#!/bin/bash

readonly SCRIPT="$(basename "$0")"

case "$1" in
  build-test)
    shift
    docker-compose build
    docker-compose run --rm test "$@"
  ;;
  test)
    shift
    docker-compose run --rm test "$@"
  ;;
  build-test-brew)
    shift
    docker-compose build
    docker-compose run --rm test-brew "$@"
  ;;
  test-brew)
    shift
    docker-compose run --rm test-brew "$@"
  ;;
  build-play)
    shift
    docker-compose build
    docker-compose run --rm play "$@"
  ;;
  play)
    shift
    docker-compose run --rm play "$@"
  ;;
  build-play-brew)
    shift
    docker-compose build
    docker-compose run --rm play-brew "$@"
  ;;
  play-brew)
    shift
    docker-compose run --rm play-brew "$@"
  ;;
  build-dotfiles)
    shift
    docker-compose build
    docker-compose run --rm dotfiles "$@"
  ;;
  dotfiles)
    shift
    docker-compose run --rm dotfiles "$@"
  ;;
  host)
    echo "hostname: $(hostname)"
  ;;
  *)
    cat <<-EOF
    $SCRIPT test
    $SCRIPT test ./dist/packages/docker/test/setup.bats
    $SCRIPT play
    $SCRIPT build-test
    $SCRIPT build-play
EOF
  ;;
esac
