version: '3.8'

x-base: &base
  env_file: .env
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      VERSION: '20.04'
      APT_PROXY: "${APT_PROXY}"
      USER: "${DUSER}"
    target: dev
  container_name: "${NAME}"
  volumes:
    - "./:${MOUNT}:ro"
  working_dir: "${WORKDIR}"
  environment: &env
    LIBS: /usr/local/lib/
  stdin_open: true # docker run -i
  tty: true        # docker run -t

services:
  test:
    <<: *base
    user: "${DUSER}"
    command: >
      bash -c '
      ./scripts/lint-shellcheck &&
      ./scripts/test-bats
      '
  stagin:
    <<: *base
    command: bash
