version: '3.8'



x-base: &base
  env_file: .env
  container_name: "${NAME}"
  working_dir: "${WORKDIR}"
  environment: &env
    LIBS: /usr/local/lib/
  stdin_open: true # docker run -i
  tty: true        # docker run -t

services:
  test:
    <<: *base
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VERSION: '20.04'
        APT_PROXY: "${APT_PROXY}"
        USER: "${DUSER}"
        WORKDIR: "${WORKDIR}"
      target: dev
    user: "${DUSER}"
    volumes:
      - "./:${MOUNT}:ro"
    command: >
      bash -c '
      ./scripts/lint-shellcheck &&
      ./scripts/test-bats
      '
  e2e:
    <<: *base
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        VERSION: '20.04'
        APT_PROXY: "${APT_PROXY}"
        USER: "${DUSER}"
        WORKDIR: "${WORKDIR}"
      target: e2e
    user: "${DUSER}"
    volumes:
      - "./.env:${WORKDIR}/.env:ro"
      - "./dist/.env:${WORKDIR}/dist/.env:ro"
    command: bash -c './dist/setup-cm desktop'
