version: '3.8'

x-build: &build
  context: .
  dockerfile: ./Dockerfile
  args:
    VERSION: '20.04'
    APT_PROXY: "${APT_PROXY}"
    USER: "${DUSER}"
    WORKDIR: "${WORKDIR}"
  target: dev

x-base: &base
  env_file: .env
  container_name: "${NAME}"
  working_dir: "${WORKDIR}"
  user: "${DUSER}"
  volumes:
    - "./:${MOUNT}:ro"
  tmpfs:
    - "${MOUNT}/dist/packages/bashc/content/.bashc/plugins/local:uid=1000,gid=1000"
    - "${MOUNT}/dist/packages/bashc/content/.bashc/gen:uid=1000,gid=1000"
  stdin_open: true # docker run -i
  tty: true        # docker run -t

services:
  test:
    <<: *base
    build:
      <<: *build
      target: dev
    entrypoint: "./scripts/test"

  prod:
    <<: *base
    build:
      <<: *build
      target: base
    entrypoint: "/bin/bash"

  dotfiles:
    <<: *base
    build:
      <<: *build
      target: base
    entrypoint: "./dist/dotfiles"

  gui:
    image: dorowu/ubuntu-desktop-lxde-vnc
    <<: *base
    ports:
      - '5900:5900'
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD}
      - USER=${DUSER}
    volumes:
      - '/dev/shm:/dev/shm'
      - "./:${MOUNT}:ro"
