version: '3.8'

x-build: &build
  context: .
  dockerfile: ./Dockerfile
  args:
    VERSION: '20.04'
    APT_PROXY: "${APT_PROXY}"
    USER: "${DUSER}"
    WORKDIR: "${WORKDIR}"
  target: dev

x-base: &base
  env_file: .env
  container_name: "${NAME}"
  working_dir: "${WORKDIR}"
  environment:
    LIBS: /usr/local/lib
  stdin_open: true # docker run -i
  tty: true        # docker run -t

services:
  test:
    <<: *base
    build:
      <<: *build
      target: dev
    user: "${DUSER}"
    volumes:
      - "./:${MOUNT}:ro"
    entrypoint: "./scripts/test"

  prod:
    <<: *base
    build:
      <<: *build
      target: prod
    user: "${DUSER}"
    volumes:
      - "./.env:${WORKDIR}/.env:ro"
      - "./dist/.env:${WORKDIR}/dist/.env:ro"
    entrypoint: "./dist/dotfiles"

