version: '3.8'

x-build: &build
  context: .
  dockerfile: ./Dockerfile
  args:
    VERSION: '20.04'
    APT_PROXY: "${APT_PROXY}"
    USER: "${DUSER}"
    WORKDIR: "${WORKDIR}"
  target: dev

x-base: &base
  env_file: .env
  container_name: "${NAME}"
  working_dir: "${WORKDIR}"
  environment:
    LIBS: /usr/local/lib/
  volumes:
    - "./:${MOUNT}:ro"
  stdin_open: true # docker run -i
  tty: true        # docker run -t

services:
  test:
    <<: *base
    build:
      <<: *build
      target: dev
    user: "${DUSER}"
    command: >
      bash -c '
      ./scripts/lint-shellcheck &&
      ./scripts/test-bats
      '
  prod:
    <<: *base
    build:
      <<: *build
      target: base
    user: "${DUSER}"
    volumes:
      - "./:${MOUNT}:ro"
      - "./packages/bash/content/.bashc/plugins/local:${MOUNT}/packages/bash/content/.bashc/plugins/local:rw"
    entrypoint: "./dist/setup-cm"

