#!/bin/bash

case "$1" in
  build-test)
    shift
    docker-compose build
    docker-compose run --rm test "$@"
  ;;
  build-prod|build-setup-cm)
    shift
    docker-compose build
    docker-compose run --rm prod "$@"
  ;;
  test)
    shift
    docker-compose run --rm test "$@"
  ;;
  prod|setup-cm)
    shift
    docker-compose run --rm prod "$@"
  ;;
  host)
    echo "hostname: $(hostname)"
  ;;
  *)
    echo "./run test"
    echo "./run bulld-test"
    exit 1
  ;;
esac
