#!/bin/bash

case "$1" in
  build-test)
    shift
    docker-compose build
    docker-compose run --rm test "$@"
  ;;
  test)
    shift
    docker-compose run --rm test "$@"
  ;;
  e2e)
    shift
    docker-compose run --rm e2e "$@"
  ;;
  *)
    echo "./run test"
    echo "./run bulld-test"
    exit 1
  ;;
esac
