#!/bin/bash

# readonly TMP_FILE="$(mktemp)"
# export TMP_FILE

# on_exit() {
#   rm "$TMP_FILE"
# }

# trap on_exit INT TERM EXIT

case "$1" in
  build-test)
    shift
    docker-compose build
    docker-compose run --rm test "$@"
  ;;
  test)
    shift
    docker-compose run --rm test "$@"
  ;;
  build-prod)
    shift
    docker-compose build
    docker-compose run --rm prod "$@"
  ;;
  prod)
    shift
    docker-compose run --rm prod "$@"
  ;;
  norm-prod)
    shift
    docker-compose run prod "$@"
  ;;
  build-dotfiles)
    shift
    docker-compose build
    docker-compose run --rm dotfiles "$@"
  ;;
  dotfiles)
    shift
    docker-compose run --rm dotfiles "$@"
  ;;
  norm-dotfiles)
    shift
    docker-compose run dotfiles "$@"
  ;;
  host)
    echo "hostname: $(hostname)"
  ;;
  *)
    echo "./run test"
    echo "./run bulld-test"
    exit 1
  ;;
esac
