#!/usr/bin/env bash

set -euE

set -o allexport
. ./.env
set +o allexport

# Install docker
wget -qO - "${iscript}/docker/docker-ubuntu" | bash
# Install Vagrant
wget -qO - "${iscript}/vagrant/vagrant-ubuntu" | bash
vagrant plugin install vagrant-aws
vagrant plugin install vagrant-readenv
