#!/bin/bash
set -e

# shellcheck disable=SC2155
export DIST_PATH="$(realpath ./dist)"

cd './dist/packages'
for pkg in *; do
  echo -e "\n> package: ${pkg}\n"

  while read -r suite; do
    echo -e 💚/💔 ">> ${suite##*/} in ${suite%/*}\n"
    bats "./$suite"
  done < <(find "${pkg}/test" -ignore_readdir_race -name '*.bats' -type f 2> /dev/null )

done

exit $?
